year_cutoff: 2010
user_agent: TenderworksOSINTBot/0.1 (+github.com/tenderworks-prodigy/yacht_osint)
drive_folder_id: ${DRIVE_FOLDER_ID}
spreadsheet_id: ${SPREADSHEET_ID}
rate_limit_rps: 1
use_wayback: true
llm:
  primary: HF
  hf_model: mistralai/Mixtral-8x7B-Instruct-v0.1
  groq_model: llama3-70b-8192
  temperature: 0
  schema_retry: 1
canonical_db_path: ${CANONICAL_DB_PATH}
