name: auto-format

on:
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

permissions:
  contents: write
  
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0                # need full history for push
          ref: ${{ github.event.pull_request.head.ref }}
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Upgrade pip & install formatters
        run: |
          pip install --upgrade pip
          # pin to a version of Ruff that has `--fix` support
          pip install 'ruff>=0.12.5' black

      - name: Apply auto-fixable Ruff rules
        run: |
          # Ruff expects the path (.) before the --fix flag
          ruff check . --fix
          # verify nothing remains to fix
          ruff check .

      - name: Apply Black formatting
        run: |
          black .

      - name: Ensure branch checked out
        run: |
          git switch "${{ github.event.pull_request.head.ref }}"

      - name: Commit & push formatting changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          # only commit if there are formatting changes
          if ! git diff --cached --quiet; then
            git commit -m "chore(auto-format): apply Ruff & Black fixes"
            git push
          fi
