name: auto-format
on:
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:    # ← allows manual “Run workflow” from the Actions tab

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true     # so we can push back to the PR branch

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install formatters
        run: pip install ruff==0.12.5 black

      - name: Apply Ruff fixes
        run: |
          ruff --fix .
          ruff .          # re-run to ensure no errors remain

      - name: Apply Black formatting
        run: black .

      - name: Commit & push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --quiet || git commit -m "chore(auto-format): apply Ruff & Black fixes"
          git push
