name: auto-format
on:
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install formatters
        run: |
          pip install ruff black

      - name: Apply Ruff auto-fixes
        run: |
          # fix what can be fixed
          ruff --fix .
          # then verify no errors remain
          ruff .

      - name: Apply Black formatting
        run: black .

      - name: Commit & push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --quiet || git commit -m "chore(auto-format): apply Ruff & Black fixes"
          git push
