name: build-ci-image

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v5
        with:
          context: .
          file: .github/docker/ci.Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/yacht-osint-ci:latest
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/yacht-osint-ci:cache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/yacht-osint-ci:cache,mode=max
