name: just_checking
on:
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    container:
      image: ghcr.io/${{ github.repository_owner }}/yacht-osint-ci:latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
    python-version: '3.x'
    
      - name: Quality gate
        run: |
          ruff check --fix .
          black --check .

      - name: Export CSV
        run: |
          python -m src.export.csv
          test -f exports/yachts.csv

      - name: Tests
        run: pytest -q --cov=src --cov-report=xml

      - name: Upload exports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: yacht-osint-exports
          path: exports/yachts.csv

      - name: Create GitHub Issue on Failure
        if: failure()
        run: |
          curl -X POST \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues \
            -d $'{
              "title": "CI failed",
              "body": "The CI pipeline failed. See logs: '"${{ github.run_url }}"'"
            }'
