name: just_checking
on:
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/${{ github.repository_owner }}/yacht-osint-ci:latest
    steps:
      - uses: actions/checkout@v4

      - name: Quality gate
        run: |
          ruff check --fix .
          black --check .

      - name: Export CSV
        run: |
          python -m src.export.csv
          test -f exports/yachts.csv

      - name: Tests
        run: pytest -q --cov=src --cov-report=xml

      - name: Upload exports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: yacht-osint-exports
          path: exports/yachts.csv
