+name: build
+on:
+  push:
+    branches: [main]
+  pull_request:
+
+jobs:
+  build:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - uses: actions/setup-python@v5
+        with:
+          python-version: '3.11'
+      - name: Install deps
+        run: pip install -r requirements.txt
+      - name: Install dev tools
+        run: pip install ruff==0.12.5 black coverage[toml]
+      - name: Quality gate
+        run: |
+          ruff check --fix .
+          black --check .
+      - name: Tests
+        run: pytest -q --cov=src --cov-report=xml
+      - name: Verify exports
+        run: |
+          python -m src.export.csv
+          test -f exports/yachts.csv
+      - name: Upload exports
+        if: always()
+        uses: actions/upload-artifact@v4
+        with:
+          name: yacht-osint-exports
+          path: exports/yachts.csv
